//! Dense variant indexing for runtime keyed dispatch.
//!
//! [`Dispatchable`] turns an enum into a dense ordinal space (`0..VARIANTS`)
//! so a dispatch table can be a flat array indexed by [`Dispatchable::ordinal`]
//! rather than a hash map. It is the substrate the pipeline dispatch
//! combinators build on, but it is also a useful `enum-map`-style primitive on
//! its own.
//!
//! Derive it with `#[derive(Dispatchable)]`. The derive also emits, for each
//! variant, a zero-sized marker type implementing [`VariantOf`] that ties the
//! variant to its payload type, its ordinal, and an unchecked unwrap. The
//! markers live in a generated module named `<enum_snake_case>_variants`:
//!
//! ```
//! use nexus_rt::{Dispatchable, VariantOf};
//!
//! #[derive(Dispatchable)]
//! enum Cmd {
//!     RouteAway(u32),
//!     Halt,
//! }
//!
//! assert_eq!(Cmd::VARIANTS, 2);
//! assert_eq!(Cmd::RouteAway(7).ordinal(), 0);
//! assert_eq!(Cmd::Halt.ordinal(), 1);
//!
//! // The caller knows the value is `RouteAway`, so the unwrap is sound.
//! let payload = unsafe { cmd_variants::RouteAway::unwrap(Cmd::RouteAway(7)) };
//! assert_eq!(payload, 7);
//! ```

/// Dense variant indexing for keyed dispatch.
///
/// Derive with `#[derive(Dispatchable)]`. The derived [`ordinal`] normalizes
/// sparse or explicit discriminants to a dense index in `0..VARIANTS`
/// following declaration order — which is why it is derived rather than
/// spelled `as usize` (`as usize` breaks on sparse reprs and does not exist
/// for data-carrying variants).
///
/// [`ordinal`]: Dispatchable::ordinal
pub trait Dispatchable {
    /// Number of variants (dense).
    const VARIANTS: usize;

    /// Variant → dense index in `0..VARIANTS` (declaration order).
    fn ordinal(&self) -> usize;
}

/// A single variant of enum `E`, as a zero-sized marker type (generated by
/// the derive).
///
/// Ties a variant to its payload type and ordinal, and provides the unchecked
/// unwrap that bridges an erased dispatch slot back to the typed arm.
pub trait VariantOf<E>: Sized {
    /// The variant's payload: `()` for a unit variant, the field type for a
    /// single-field variant, or a tuple of the field types for a multi-field
    /// tuple variant.
    type Payload;

    /// This variant's dense ordinal (matches [`Dispatchable::ordinal`]).
    const ORDINAL: usize;

    /// Extract this variant's payload from `e` without checking the
    /// discriminant.
    ///
    /// # Safety
    /// Caller guarantees `e` is this variant (upheld by dispatching on `e`'s
    /// own discriminant). If `e` is a different variant this is undefined
    /// behavior; debug builds trip a `debug_assert!` first.
    unsafe fn unwrap(e: E) -> Self::Payload;
}
